version: '2.1'
services:

  # The Application
  app:
    container_name: app
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "PHP_MEMORY_LIMIT=-1"
      - "DB_PORT=3306"
      - "DB_HOST=db"

  # The Web Server
  web:
    container_name: web 
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  # The Database
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "3306:3306"

volumes:
  dbdata:
